# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 5.0.101 # optional
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Build site
      run: |
        choco install docfx 2.56.1 -y
        docfx metadata
        docfx metadata
        docfx build
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Configure git bot information
      run: |
        git config user.name Ultz
        git config user.email 31213871+UltzLtd@users.noreply.github.com
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Configure git repository
      run: |
        git remote set-url origin "https://UltzLtd:${{ secrets.ULTZLTD_TOKEN }}@github.com/Ultz/docs.ultz.co.uk"
        git fetch
        git add docs/
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Commit and publish site
      run: |
        git commit -m "Site rebuild for ${{ github.run_number }}"
        git push origin HEAD:master
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
